-- MySQL Script generated by MySQL Workbench
-- Fri Mar 24 15:04:24 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SGPF
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SGPF
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SGPF` DEFAULT CHARACTER SET utf8 ;
USE `SGPF` ;

-- -----------------------------------------------------
-- Table `SGPF`.`programaFormacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGPF`.`programaFormacion` (
  `idProgramaFormacion` INT NOT NULL AUTO_INCREMENT,
  `nombrePrograma` VARCHAR(50) NOT NULL,
  `ficha` INT NOT NULL,
  PRIMARY KEY (`idProgramaFormacion`),
  UNIQUE INDEX `ficha_UNIQUE` (`ficha` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGPF`.`proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGPF`.`proyecto` (
  `idProyecto` INT NOT NULL AUTO_INCREMENT,
  `idProgramaFormacion` INT NOT NULL,
  `nombreProyecto` VARCHAR(80) NOT NULL,
  `objetivoGeneral` VARCHAR(255) NOT NULL,
  `estado` VARCHAR(15) NOT NULL,
  `planteamientoProblema` TEXT NOT NULL,
  `justificacion` TEXT NOT NULL,
  `funcionalidades` TEXT NOT NULL,
  `alcances` TEXT NOT NULL,
  `archivo` VARCHAR(255) NOT NULL,
  `cliente` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idProyecto`, `idProgramaFormacion`),
  INDEX `fk_proyecto_programaFormacion1_idx` (`idProgramaFormacion` ASC),
  CONSTRAINT `fk_proyecto_programaFormacion1`
    FOREIGN KEY (`idProgramaFormacion`)
    REFERENCES `SGPF`.`programaFormacion` (`idProgramaFormacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGPF`.`instructor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGPF`.`instructor` (
  `idInstructor` INT NOT NULL AUTO_INCREMENT,
  `nombreInstructor` VARCHAR(50) NOT NULL,
  `apellidoInstructor` VARCHAR(50) NOT NULL,
  `tipoDocumento` VARCHAR(10) NOT NULL,
  `numeroDocumento` VARCHAR(13) NOT NULL,
  PRIMARY KEY (`idInstructor`),
  UNIQUE INDEX `numeroDocumento_UNIQUE` (`numeroDocumento` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGPF`.`aprendiz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGPF`.`aprendiz` (
  `idAprendiz` INT NOT NULL AUTO_INCREMENT,
  `idProgramaFormacion` INT NOT NULL,
  `nombreAprendiz` VARCHAR(50) NOT NULL,
  `apellidoAprendiz` VARCHAR(50) NOT NULL,
  `tipoDocumento` VARCHAR(10) NOT NULL,
  `numeroDocumento` VARCHAR(13) NOT NULL,
  `estado` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idAprendiz`, `idProgramaFormacion`),
  INDEX `fk_aprendiz_programaFormacion1_idx` (`idProgramaFormacion` ASC),
  UNIQUE INDEX `numeroDocumento_UNIQUE` (`numeroDocumento` ASC),
  CONSTRAINT `fk_aprendiz_programaFormacion1`
    FOREIGN KEY (`idProgramaFormacion`)
    REFERENCES `SGPF`.`programaFormacion` (`idProgramaFormacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGPF`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGPF`.`rol` (
  `idRol` INT NOT NULL AUTO_INCREMENT,
  `rol` VARCHAR(15) NOT NULL,
  `codigo` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idRol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGPF`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGPF`.`usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `idRol` INT NOT NULL,
  `usuario` VARCHAR(30) NOT NULL,
  `contrasena` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idUsuario`, `idRol`),
  INDEX `fk_usuario_rol_idx` (`idRol` ASC),
  CONSTRAINT `fk_usuario_rol`
    FOREIGN KEY (`idRol`)
    REFERENCES `SGPF`.`rol` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGPF`.`fase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGPF`.`fase` (
  `idFase` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(10) NOT NULL,
  `competencia` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idFase`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGPF`.`objetivosEspecificos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGPF`.`objetivosEspecificos` (
  `idObjetivosEspecificos` INT NOT NULL AUTO_INCREMENT,
  `idProyecto` INT NOT NULL,
  `objetivo` TEXT NOT NULL,
  PRIMARY KEY (`idObjetivosEspecificos`, `idProyecto`),
  INDEX `fk_objetivosEspecificos_fichaProyecto1_idx` (`idProyecto` ASC),
  CONSTRAINT `fk_objetivosEspecificos_fichaProyecto1`
    FOREIGN KEY (`idProyecto`)
    REFERENCES `SGPF`.`proyecto` (`idProyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGPF`.`proyecto_Instructor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGPF`.`proyecto_Instructor` (
  `idProyecto` INT NOT NULL,
  `idInstructor` INT NOT NULL,
  `idFase` INT NOT NULL,
  PRIMARY KEY (`idProyecto`, `idInstructor`, `idFase`),
  INDEX `fk_instructor_has_fichaProyecto_fichaProyecto1_idx` (`idProyecto` ASC),
  INDEX `fk_instructor_has_fichaProyecto_instructor1_idx` (`idInstructor` ASC),
  INDEX `fk_fichaProyectoInstructor_fase1_idx` (`idFase` ASC),
  CONSTRAINT `fk_instructor_has_fichaProyecto_instructor1`
    FOREIGN KEY (`idInstructor`)
    REFERENCES `SGPF`.`instructor` (`idInstructor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_instructor_has_fichaProyecto_fichaProyecto1`
    FOREIGN KEY (`idProyecto`)
    REFERENCES `SGPF`.`proyecto` (`idProyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fichaProyectoInstructor_fase1`
    FOREIGN KEY (`idFase`)
    REFERENCES `SGPF`.`fase` (`idFase`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGPF`.`participantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGPF`.`participantes` (
  `idProyecto` INT NOT NULL,
  `idAprendiz` INT NOT NULL,
  PRIMARY KEY (`idProyecto`, `idAprendiz`),
  INDEX `fk_aprendiz_has_fichaProyecto_fichaProyecto1_idx` (`idProyecto` ASC),
  INDEX `fk_aprendiz_has_fichaProyecto_aprendiz1_idx` (`idAprendiz` ASC),
  CONSTRAINT `fk_aprendiz_has_fichaProyecto_aprendiz1`
    FOREIGN KEY (`idAprendiz`)
    REFERENCES `SGPF`.`aprendiz` (`idAprendiz`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aprendiz_has_fichaProyecto_fichaProyecto1`
    FOREIGN KEY (`idProyecto`)
    REFERENCES `SGPF`.`proyecto` (`idProyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
