-- MySQL Script generated by MySQL Workbench
-- Tue Mar 14 18:42:08 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sgpf_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sgpf_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sgpf_db` DEFAULT CHARACTER SET utf8 ;
USE `sgpf_db` ;

-- -----------------------------------------------------
-- Table `sgpf_db`.`proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgpf_db`.`proyecto` (
  `idProyecto` INT NOT NULL AUTO_INCREMENT,
  `nombreProyecto` VARCHAR(80) NOT NULL,
  `objetivoGeneral` VARCHAR(255) NOT NULL,
  `estado` VARCHAR(15) NOT NULL,
  `planteamientoProblema` TEXT NOT NULL,
  `justificacion` TEXT NOT NULL,
  `funcionalidades` TEXT NOT NULL,
  `alcances` TEXT NOT NULL,
  `archivo` VARCHAR(255) NOT NULL,
  `cliente` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idProyecto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgpf_db`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgpf_db`.`rol` (
  `idRol` INT NOT NULL AUTO_INCREMENT,
  `rol` VARCHAR(15) NOT NULL,
  `codigo` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idRol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgpf_db`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgpf_db`.`usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `idRol` INT NOT NULL,
  `usuario` VARCHAR(30) NOT NULL,
  `contrasena` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idUsuario`, `idRol`),
  INDEX `fk_usuario_rol_idx` (`idRol` ASC),
  CONSTRAINT `fk_usuario_rol`
    FOREIGN KEY (`idRol`)
    REFERENCES `sgpf_db`.`rol` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgpf_db`.`instructor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgpf_db`.`instructor` (
  `idInstructor` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NOT NULL,
  `nombreInstructor` VARCHAR(50) NOT NULL,
  `apellidoInstructor` VARCHAR(50) NOT NULL,
  `tipoDocumento` VARCHAR(10) NOT NULL,
  `numeroDocumento` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idInstructor`, `idUsuario`),
  INDEX `fk_instructor_usuario1_idx` (`idUsuario` ASC),
  CONSTRAINT `fk_instructor_usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `sgpf_db`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgpf_db`.`programaFormacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgpf_db`.`programaFormacion` (
  `idProgramaFormacion` INT NOT NULL AUTO_INCREMENT,
  `nombrePrograma` VARCHAR(50) NOT NULL,
  `ficha` INT NOT NULL,
  PRIMARY KEY (`idProgramaFormacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgpf_db`.`aprendiz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgpf_db`.`aprendiz` (
  `idAprendiz` INT NOT NULL AUTO_INCREMENT,
  `idProgramaFormacion` INT NOT NULL,
  `nombreAprendiz` VARCHAR(50) NOT NULL,
  `apellidoAprendiz` VARCHAR(50) NOT NULL,
  `tipoDocumento` VARCHAR(10) NOT NULL,
  `numeroDocumento` VARCHAR(30) NOT NULL,
  `estado` VARCHAR(15) NOT NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idAprendiz`, `idProgramaFormacion`, `idUsuario`),
  INDEX `fk_aprendiz_usuario1_idx` (`idUsuario` ASC),
  INDEX `fk_aprendiz_programaFormacion1_idx` (`idProgramaFormacion` ASC),
  CONSTRAINT `fk_aprendiz_usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `sgpf_db`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aprendiz_programaFormacion1`
    FOREIGN KEY (`idProgramaFormacion`)
    REFERENCES `sgpf_db`.`programaFormacion` (`idProgramaFormacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgpf_db`.`fase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgpf_db`.`fase` (
  `idFase` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(10) NOT NULL,
  `competencia` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idFase`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgpf_db`.`objetivosEspecificos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgpf_db`.`objetivosEspecificos` (
  `idObjetivosEspecificos` INT NOT NULL AUTO_INCREMENT,
  `idProyecto` INT NOT NULL,
  `objetivo` TEXT NOT NULL,
  PRIMARY KEY (`idObjetivosEspecificos`, `idProyecto`),
  INDEX `fk_objetivosEspecificos_fichaProyecto1_idx` (`idProyecto` ASC),
  CONSTRAINT `fk_objetivosEspecificos_fichaProyecto1`
    FOREIGN KEY (`idProyecto`)
    REFERENCES `sgpf_db`.`proyecto` (`idProyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgpf_db`.`proyecto_Instructor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgpf_db`.`proyecto_Instructor` (
  `idProyecto` INT NOT NULL,
  `idInstructor` INT NOT NULL,
  `idFase` INT NOT NULL,
  PRIMARY KEY (`idProyecto`, `idInstructor`, `idFase`),
  INDEX `fk_instructor_has_fichaProyecto_fichaProyecto1_idx` (`idProyecto` ASC),
  INDEX `fk_instructor_has_fichaProyecto_instructor1_idx` (`idInstructor` ASC),
  INDEX `fk_fichaProyectoInstructor_fase1_idx` (`idFase` ASC),
  CONSTRAINT `fk_instructor_has_fichaProyecto_instructor1`
    FOREIGN KEY (`idInstructor`)
    REFERENCES `sgpf_db`.`instructor` (`idInstructor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_instructor_has_fichaProyecto_fichaProyecto1`
    FOREIGN KEY (`idProyecto`)
    REFERENCES `sgpf_db`.`proyecto` (`idProyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fichaProyectoInstructor_fase1`
    FOREIGN KEY (`idFase`)
    REFERENCES `sgpf_db`.`fase` (`idFase`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgpf_db`.`participantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgpf_db`.`participantes` (
  `idProyecto` INT NOT NULL,
  `idAprendiz` INT NOT NULL,
  PRIMARY KEY (`idProyecto`, `idAprendiz`),
  INDEX `fk_aprendiz_has_fichaProyecto_fichaProyecto1_idx` (`idProyecto` ASC),
  INDEX `fk_aprendiz_has_fichaProyecto_aprendiz1_idx` (`idAprendiz` ASC),
  CONSTRAINT `fk_aprendiz_has_fichaProyecto_aprendiz1`
    FOREIGN KEY (`idAprendiz`)
    REFERENCES `sgpf_db`.`aprendiz` (`idAprendiz`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aprendiz_has_fichaProyecto_fichaProyecto1`
    FOREIGN KEY (`idProyecto`)
    REFERENCES `sgpf_db`.`proyecto` (`idProyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
